version: "3.9"

services:
  tarefeiro:
    build: .
    container_name: tarefeiro
    volumes:
      - tarefeiro-data:/data
    environment:
      - TAREFEIRO_DATA_FILE=/data/tasks.json
    stdin_open: true
    tty: true
volumes:
  tarefeiro-data:
